In [1]:
import numpy as np

In [2]:
arr1=np.array(6)

In [3]:
arr1

array(6)

In [4]:
type(arr1)

numpy.ndarray

In [39]:
arr2=np.array([[2,3],[5,8],[3,9]])

In [40]:
arr2

array([[2, 3],
       [5, 8],
       [3, 9]])

##  array types
1.zero array

2.ones array

3.empty array

4.array for range

In [41]:
zero_array=np.zeros(2)

In [42]:
zero_array

array([0., 0.])

In [43]:
arr3=np.arange(6)

In [44]:
arr3

array([0, 1, 2, 3, 4, 5])

In [45]:
arr3=np.arange(2,16,2)

In [46]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14])

In [47]:
arr4=np.transpose(arr2)

In [48]:
arr4

array([[2, 5, 3],
       [3, 8, 9]])

In [49]:
a1=np.array([2,2])
a2=np.array([4,5])

In [50]:
a1

array([2, 2])

In [51]:
a2

array([4, 5])

In [54]:
concat=np.concatenate((a1,a2))

In [55]:
concat

array([2, 2, 4, 5])

In [52]:
hori=np.hstack((a1,a2))

In [53]:
hori

array([2, 2, 4, 5])

In [56]:
veri=np.vstack((a1,a2))

In [57]:
veri

array([[2, 2],
       [4, 5]])