In [2]:
import numpy as np

In [3]:
arr1=np.array(6)

In [4]:
arr1

array(6)

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[2,3],[5,8],[3,9]])

In [7]:
arr2

array([[2, 3],
       [5, 8],
       [3, 9]])

##  array types
1.zero array

2.ones array

3.empty array

4.array for range

In [8]:
zero_array=np.zeros(2)

In [9]:
zero_array

array([0., 0.])

In [10]:
arr3=np.arange(6)

In [11]:
arr3

array([0, 1, 2, 3, 4, 5])

In [12]:
arr3=np.arange(2,16,2)

In [13]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14])

In [14]:
arr4=np.transpose(arr2)

In [15]:
arr4

array([[2, 5, 3],
       [3, 8, 9]])

In [16]:
a1=np.array([2,2])
a2=np.array([4,5])

In [17]:
a1

array([2, 2])

In [18]:
a2

array([4, 5])

In [19]:
concat=np.concatenate((a1,a2))

In [20]:
concat

array([2, 2, 4, 5])

In [21]:
hori=np.hstack((a1,a2))

In [22]:
hori

array([2, 2, 4, 5])

In [23]:
veri=np.vstack((a1,a2))

In [24]:
veri

array([[2, 2],
       [4, 5]])

In [34]:
mat1=np.array([[3,4],[1,2]])

In [35]:
mat1

array([[3, 4],
       [1, 2]])

In [36]:
det_of_mat1=np.linalg.det(mat1)

In [37]:
det_of_mat1

2.0000000000000004

In [38]:
inverse=np.linalg.det(mat1)

In [39]:
inverse

2.0000000000000004

In [40]:
dense=np.array(([1,0,0,0],[1,2,0,0],[2,0,0,1],[2,0,0,0]))

In [41]:
dense

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [2, 0, 0, 1],
       [2, 0, 0, 0]])

In [42]:
from scipy.sparse import csr_matrix

In [43]:
sparse=csr_matrix(dense)

In [44]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 6 stored elements in Compressed Sparse Row format>

In [45]:
print(sparse)

  (0, 0)	1
  (1, 0)	1
  (1, 1)	2
  (2, 0)	2
  (2, 3)	1
  (3, 0)	2
